version: "3.7"

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdb-data:/var/lib/postgresql/data/
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
  backend:
    container_name: ripio_backend
    build:
      context: ./ripio
      dockerfile: backend.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./travel-backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - postgresdb
        # condition: service_healthy
  frontend:
    container_name: ripio_frontend
    build:
      context: ./ripio_react
      dockerfile: frontend.Dockerfile
    command: ["yarn", "start"]
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgresdb-data:
